### ISSUE TITLE
Is this an error?

### ISSUE THREAD

**Issue by andyyuan78** [yajiemiao/pdnn#12]
ubgpu@ubgpu:~/github/pdnn/examples/mnist_rbm$ sudo ./run.sh 
--2015-05-16 15:48:05--  http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz
Resolving www.iro.umontreal.ca (www.iro.umontreal.ca)... 132.204.24.179
Connecting to www.iro.umontreal.ca (www.iro.umontreal.ca)|132.204.24.179|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16168813 (15M) [application/x-gzip]
Saving to: 鈥榤nist.pkl.gz.6鈥

100%[===============================================================================================================================================================>] 16,168,813  2.98MB/s   in 5.5s   

2015-05-16 15:48:11 (2.81 MB/s) - 鈥榤nist.pkl.gz.6鈥saved [16168813/16168813]

Preparing datasets ...
Traceback (most recent call last):
  File "data_prep.py", line 9, in <module>
    train_set, valid_set, test_set = cPickle.load(f)
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x3d667246 != 0x7f91b084L
Training the RBM model ...
ubgpu@ubgpu:~/github/pdnn/examples/mnist_rbm$ 
ubgpu@ubgpu:~/github/pdnn/examples/mnist_rbm$

**Comment by intfloat** [comment]
`IOError: CRC check failed 0x3d667246 != 0x7f91b084L`

It indicates your downloaded data file contains error, nothing to do with the code, you may delete plk.gz file and try again.
